# -*- coding: utf-8 -*-
"""Automatic-Essay-Scoring (AES)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xq8GExwp8a-D01z4Qe1UZ-VtwV0KcePi
"""

!pip install transformers datasets scikit-learn

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from datasets import Dataset
import torch
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/Automated student assessment prize..csv")

df.shape

df.head()

df.drop(columns=["essay_id"], inplace=True)

df.isnull().sum()

plt.figure(figsize=(8,5))
sns.histplot(df['score'], kde=True, bins=10, color='teal')
plt.title('Essay Score Distribution')
plt.xlabel('Score')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

df['essay_length'] = df['full_text'].apply(lambda x: len(str(x).split()))

plt.figure(figsize=(8,5))
sns.histplot(df['essay_length'], kde=True, bins=30, color='orange')
plt.title('Essay Length Distribution')
plt.xlabel('Number of Words')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

import re
import string

def clean_text(text):
    text = text.lower()
    text = re.sub(r'\n', ' ', text)
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub(r'<.*?>+', '', text)
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub(r'\w*\d\w*', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['full_text'] = df['full_text'].apply(clean_text)

# Print cleaned text
df['full_text'].head()

from sklearn.model_selection import train_test_split

X = df['full_text']
y = df['score']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

train_encodings = tokenizer(list(X_train), truncation=True, padding=True, max_length=512)
test_encodings = tokenizer(list(X_test), truncation=True, padding=True, max_length=512)

import torch

class EssayDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            key: torch.tensor(val[idx]) for key, val in self.encodings.items()
        } | {
            'labels': torch.tensor(self.labels[idx], dtype=torch.float)
        }

train_dataset = EssayDataset(train_encodings, list(y_train))
test_dataset = EssayDataset(test_encodings, list(y_test))

!pip install transformers datasets evaluate

from sklearn.model_selection import train_test_split

# Split into train and validation
train_texts, val_texts, train_labels, val_labels = train_test_split(
    df['full_text'].tolist(),
    df['score'].tolist(),
    test_size=0.2,
    random_state=42
)

from transformers import AutoTokenizer

model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

train_encodings = tokenizer(train_texts, truncation=True, padding=True, return_tensors="pt")
val_encodings = tokenizer(val_texts, truncation=True, padding=True, return_tensors="pt")

import torch

class EssayDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = torch.tensor(labels, dtype=torch.float)

    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items()}
        item['labels'] = self.labels[idx]
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = EssayDataset(train_encodings, train_labels)
val_dataset = EssayDataset(val_encodings, val_labels)

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=1  # For regression
)

from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    logging_dir='./logs',
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
)

trainer.train()

results = trainer.evaluate()
print(results)

from sklearn.metrics import accuracy_score, f1_score, mean_squared_error

def predict(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
    output = model(**inputs)
    return output.logits

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Get predictions from the model
predictions = trainer.predict(test_dataset)

# Extract predicted scores and true labels
y_pred = predictions.predictions.squeeze()
y_true = predictions.label_ids.squeeze()

# Calculate metrics
mse = mean_squared_error(y_true, y_pred)
mae = mean_absolute_error(y_true, y_pred)
r2 = r2_score(y_true, y_pred)

print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"R² Score: {r2:.4f}")

import matplotlib.pyplot as plt

# Metrics
metrics = ['MSE', 'MAE', 'R²']
values = [0.3480, 0.4558, 0.6846]

# Plot
plt.bar(metrics, values, color=['skyblue', 'lightgreen', 'salmon'])
plt.title('Regression Metrics')
plt.ylabel('Score')
plt.ylim(0, 1)  # Keep scale consistent
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
plt.scatter(y_true, y_pred, alpha=0.5)
plt.xlabel("Actual Essay Scores")
plt.ylabel("Predicted Essay Scores")
plt.title("Predicted vs. Actual Essay Scores")
plt.plot([min(y_true), max(y_true)], [min(y_true), max(y_true)], color='red')  # identity line
plt.grid(True)
plt.show()

# Scatter plot: Predicted vs Actual
plt.figure(figsize=(6, 6))
sns.scatterplot(x=y_true, y=y_pred)
plt.xlabel("Actual Score")
plt.ylabel("Predicted Score")
plt.title("Predicted vs Actual Essay Scores")
plt.plot([min(y_true), max(y_true)], [min(y_true), max(y_true)], color='red')
plt.show()

#Residual histogram
residuals = np.array(y_true) - np.array(y_pred)
plt.figure(figsize=(6, 4))
sns.histplot(residuals, kde=True)
plt.title("Distribution of Residuals (Errors)")
plt.xlabel("Error")
plt.ylabel("Frequency")
plt.show()

import joblib

# Save model
joblib.dump(model, 'essay_scoring_model.pkl')

import joblib

model = joblib.load("essay_scoring_model.pkl")